# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 20:19
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('\u0432\u044b\u0445\u043e\u0434\u043d\u043e\u0439', '\u0432\u044b\u0445\u043e\u0434\u043d\u043e\u0439'), ('\u0431\u043e\u043b\u044c\u043d\u0438\u0447\u043d\u044b\u0439', '\u0431\u043e\u043b\u044c\u043d\u0438\u0447\u043d\u044b\u0439')], default='\u0432\u044b\u0445\u043e\u0434\u043d\u043e\u0439', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField(blank=True, validators=[app.models.validate_salary])),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
            bases=(models.Model, app.models.AbstractModel),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_salary', models.IntegerField()),
            ],
            bases=(models.Model, app.models.AbstractModel),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(blank=True)),
                ('finish_date', models.DateField(blank=True)),
                ('status', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=20)),
                ('wasted_days', models.IntegerField(null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
            bases=(models.Model, app.models.AbstractModel),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Position'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
        ),
    ]
