# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160418_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
