# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160419_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creationDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finishDate',
            field=models.DateField(blank=True),
        ),
    ]
