# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160419_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, default=100000),
            preserve_default=False,
        ),
    ]
