# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_salary'),
        ('app', '0003_auto_20160419_0018'),
    ]

    operations = [
    ]
