# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='finishDate',
            new_name='finish_date',
        ),
    ]
