# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160423_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wasted_days',
            field=models.IntegerField(null=True),
        ),
    ]
