# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_task_wasted_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='min_salary',
            field=models.IntegerField(default=6500),
            preserve_default=False,
        ),
    ]
