# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_task_wasted_days'),
        ('app', '0006_merge'),
    ]

    operations = [
    ]
