# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 19:43
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_position_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, validators=[app.models.validate_salary]),
        ),
        migrations.AlterField(
            model_name='position',
            name='min_salary',
            field=models.IntegerField(validators=[app.models.validate_salary]),
        ),
    ]
