# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge'),
        ('app', '0009_auto_20160425_1943'),
    ]

    operations = [
    ]
