# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 20:00
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160427_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPosTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, app.models.AbstractModel),
        ),
    ]
