# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge'),
        ('app', '0011_auto_20160427_2025'),
    ]

    operations = [
    ]
